### ISSUE TITLE
folder missing

### ISSUE THREAD

**Issue by mutagobwa** [Vonage/vonage-php-code-snippets#43]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\nexmo-php-code-snippets-master\config.php on line 2

**Comment by mutagobwa** [comment]
Some one to help me fix this. I need to test sms service from localhost

**Comment by lornajane** [comment]
Can you double check the installation steps please? The `composer install` step should create a `vendor` directory with the autoloader present. Check also that the paths make sense on your system (it's possible this hasn't been used a lot on Windows)

If you still find things don't work please let us know:
 - what version of PHP you are using
 - what's in your `vendor/` directory
 - which snippet you are trying to use

**Comment by dragonmantank** [comment]
To tack onto this, because the README doesn't specify how to use this repository exactly:

1. Most examples assume you have run `composer install` in the root of the repository, and you have configured your `.env` file correctly
2. Some larger examples may have their own subdirectory with their own `composer.json`, you will need to run `composer install` there as well.

**Comment by lornajane** [comment]
Closing after inactivity but do re-open if you need anything further on this.
